name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - name: setup redis
      uses: zhulik/redis-action@v1.0.0
    - uses: actions/checkout@v1
    - name: set node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install
      uses: Borales/actions-yarn@v2.1.0
      with:
        cmd: install
    - name: yarn test
      uses: Borales/actions-yarn@v2.1.0
      with:
        cmd: test

  deploy-upm-api:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
    - name: deploy
      uses: maddox/actions/ssh@master
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        HOST: ${{ secrets.HOST_UPM_API }}
        USER: ${{ secrets.USER }}
      with:
        args: |
            cd /home/openupm/openupm
            git pull
            yarn
            git log -m --name-only -1 --pretty="format:" --first-parent master | grep -sqE '^app|^config|^server' && pm2 reload all || echo skip pm2 api reload

  deploy-upm-build:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
    - name: deploy
      uses: maddox/actions/ssh@master
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        HOST: ${{ secrets.HOST_UPM_BUILD }}
        USER: ${{ secrets.USER }}
      with:
        args: |
            cd /home/openupm/openupm
            git pull
            yarn
            git log -m --name-only -1 --pretty="format:" --first-parent master | grep -sqE '^app|^config' && pm2 reload queue-main || echo skip pm2 queue-main reload
            git log -m --name-only -1 --pretty="format:" --first-parent master | grep -sqE '^app|^config|^data' && pm2 reload pkg-build || echo skip pm2 pkg-build reload
