name: deploy

on: [push]

jobs:
  deploy-upm-api:
    runs-on: ubuntu-latest
    steps:
    - name: deploy
      uses: maddox/actions/ssh@master
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        HOST: ${{ secrets.HOST_UPM_API }}
        USER: ${{ secrets.USER }}
      with:
        args: |
            cd /home/openupm/openupm
            git pull
            git log --name-only -1 |grep -sqE '^app|^config|^server' && pm2 reload all
  deploy-upm-build:
    runs-on: ubuntu-latest
    steps:
    - name: deploy
      uses: maddox/actions/ssh@master
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        HOST: ${{ secrets.HOST_UPM_BUILD }}
        USER: ${{ secrets.USER }}
      with:
        args: |
            cd /home/openupm/openupm
            git pull
            git log --name-only -1 |grep -sqE '^app|^config' && pm2 reload queue-main
            git log --name-only -1 |grep -sqE '^app|^config|^data' && pm2 reload pkg-build
